version: '3'
services:
  backend:
    build: 
      context: ./PartieBack
    ports:
      - "5000:5000"
    volumes:
      - ./PartieBack:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: 
      context: ./PartieFront
    ports:
      - "3000:3000"
    volumes:
      - ./PartieFront:/app
    environment:
      - NODE_ENV=development
